name: Deploy Frontend
on:
  push:
    branches:
      - prod
    paths:
      - 'frontend/anti-fake-news/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/anti-fake-news
          push: true
          tags: rattikan042/se331-frontend:latest
          
      - name: Create remote frontend directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/${{ secrets.HOST_USER_NAME }}/frontend
            
      - name: Copy docker-compose via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "frontend/anti-fake-news/docker-compose.yml"
          target: "/home/${{ secrets.HOST_USER_NAME }}/frontend"
          overwrite: true
          
      - name: Verify file copied
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "📁 Checking frontend directory:"
            ls -la /home/${{ secrets.HOST_USER_NAME }}/frontend/
            
      - name: Install Docker and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.HOST_USER_NAME }}/frontend
            
            # ติดตั้ง Docker ถ้ายังไม่มี
            if ! command -v docker &> /dev/null; then
              echo "🔍 Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
            fi
            
            # ติดตั้ง Docker Compose ถ้ายังไม่มี
            if ! command -v docker-compose &> /dev/null; then
              echo "🔍 Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            echo "🔍 Docker versions:"
            docker --version
            docker-compose --version
            
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            
            # Deploy
            docker-compose down || true
            docker-compose pull
            docker-compose up -d
            
            echo "✅ Frontend deployment completed!"